fixes

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -6,6 +6,14 @@ set -euo pipefail
 [[ -z ${ASDF_INSTALL_VERSION+x} ]] && echo "ASDF_INSTALL_VERSION is required" && exit 1
 [[ -z ${ASDF_INSTALL_PATH+x} ]] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
+function create_wrapper_script() {
+  local script_name=$1
+  local target_command=$2
+
+  printf '#!/bin/sh\nexec "%s"\n' "$target_command" > "bin/$script_name"
+  chmod +x "bin/$script_name"
+}
+
 function install() {
   local install_type=$1
   local version=$2
@@ -29,9 +37,19 @@ function install() {
 
   unzip "${tmp_download_dir}/${download_filename}"
   mkdir -p ./bin
+
+  if [[ -e debugger.sh ]]; then
+    local debug_file=debugger.sh
+  elif [[ -e debug_adapter.sh ]]; then
+    local debug_file=debug_adapter.sh
+  else
+    echo >&2 'Missing a valid elixir-ls-debugger file'; exit 1
+  fi
+
+  create_wrapper_script "elixir-ls" "${install_path}/language_server.sh"
+  create_wrapper_script "elixir-ls-debugger" "${install_path}/${debug_file}"
+
   cp -fpr * "${install_path}"
-  ln -s "${install_path}"/language_server.sh "${install_path}/bin/elixir-ls"
-  ln -s "${install_path}"/debug_adapter.sh "${install_path}/bin/elixir-ls-debug-adapter"
 
   popd >/dev/null
   popd >/dev/null
